name: Celeste-status PHP

on: [workflow_dispatch]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: true

      backend_directory: .
